apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-app-config
  namespace: video-processor
data:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres123@host.docker.internal:5432/auth_db"
  REDIS_URL: "redis://host.docker.internal:6379/0"
