apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: video-processor
spec:
  $patch: replace
  selector:
    app: auth-service
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
      nodePort: 32513
